### ISSUE TITLE
Charts not working in Firefox

### ISSUE THREAD

**Issue by konstanto** [tomspeak/polled.io#1]
![skaermbillede 2014-11-17 kl 21 53 52](https://cloud.githubusercontent.com/assets/5860524/5077505/3c884aa2-6ea4-11e4-8c68-505f525d67a6.png)
Really cool work! But charts are not shown in FF 33.1 due to lack of width in ".js-bar"-container. (width is 0px)

**Comment by tomspeak** [comment]
Will be fixed as part of the 2.0.0 react rewrite.
